// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile(arg1) {
  return window['go']['main']['App']['ChooseFile'](arg1);
}

export function ChooseOTAFile() {
  return window['go']['main']['App']['ChooseOTAFile']();
}

export function ChooseOutputDirectory() {
  return window['go']['main']['App']['ChooseOutputDirectory']();
}

export function Confirm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Confirm'](arg1, arg2, arg3, arg4);
}

export function DefaultOutputDirectory() {
  return window['go']['main']['App']['DefaultOutputDirectory']();
}

export function Devices() {
  return window['go']['main']['App']['Devices']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Inspect(arg1) {
  return window['go']['main']['App']['Inspect'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function State() {
  return window['go']['main']['App']['State']();
}
