// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';
import {main} from '../models';

export function ChooseFile(arg1:string):Promise<string>;

export function ChooseOTAFile():Promise<string>;

export function ChooseOutputDirectory():Promise<string>;

export function Confirm(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function DefaultOutputDirectory():Promise<string>;

export function Devices():Promise<Array<device.Device>>;

export function GetSettings():Promise<main.Settings>;

export function Inspect(arg1:string):Promise<device.Device>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Start(arg1:main.InstallRequest):Promise<void>;

export function State():Promise<main.TaskState>;
